function(exclude_files from_sources_list matching_patterns)
    foreach(_matching_pattern IN ITEMS ${matching_patterns})
        foreach(_source IN ITEMS ${${from_sources_list}})
            if (${_source} MATCHES ${_matching_pattern})
                list(REMOVE_ITEM ${from_sources_list} ${_source})
            endif()
        endforeach()
    endforeach()
    set(${from_sources_list} ${${from_sources_list}} PARENT_SCOPE)
endfunction()
