function (fill_platform_excludes out_patterns)
    if (WIN32)
        list(APPEND ${out_patterns} ".*\\.linux.*" ".*\\.macos.*")
    elseif (APPLE)
        list(APPEND ${out_patterns} ".*\\.linux.*" ".*\\.win.*")
    elseif (UNIX)
        list(APPEND ${out_patterns} ".*\\.macos.*" ".*\\.win.*")
    endif()
    set(${out_patterns} ${${out_patterns}} PARENT_SCOPE)
endfunction()
