function(gather_subdirs results from_root)
    file(GLOB children RELATIVE ${from_root} ${from_root}/*)
    foreach(child ${children})
        if (IS_DIRECTORY ${from_root}/${child})
            list(APPEND ${results} ${child})
        endif()
    endforeach()
    set(${results} ${${results}} PARENT_SCOPE)
endfunction()
