if (${project_config_use_unit_tests})
    include("cmake_utils/setup_gtest.cmake")
endif()
if (${project_config_use_benchmark})
    include("cmake_utils/setup_benchmark.cmake")
endif()
if (${project_config_use_clang_tidy})
    include("cmake_utils/setup_clang_tidy.cmake")
endif()
