### Enable VS folders
set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER _cmake_targets)

function(setup_visual_studio_filters erase_tokens for_files)
    foreach (_source IN ITEMS ${${for_files}})
        if (IS_ABSOLUTE "${_source}")
            file(RELATIVE_PATH _source_rel "${CMAKE_CURRENT_SOURCE_DIR}/.." "${_source}")
        else()
            set(_source_rel "${_source}")
        endif()
        get_filename_component(_source_path "${_source_rel}" PATH)
        string(REPLACE "\\" "/" _source_path_vs "${_source_path}")
        foreach (_token IN ITEMS ${erase_tokens})
            string(REPLACE "${_token}/" "" _source_path_vs "${_source_path_vs}")
            string(REPLACE "${_token}" "" _source_path_vs "${_source_path_vs}")
        endforeach()
        source_group("${_source_path_vs}" FILES "${_source}")
    endforeach()
endfunction()
